### PR TITLE
Design improvements

### PR DESCRIPTION
**Pull request by vladstudio**
Initially I wanted to do minor tweaks of some colors, fonts, line height, etc. But I could not stop in time, and ended up changing quite a lot of code!

In my eyes, it all makes sense; however I do understand you might have different vision. Feel free to reject, of course. Still, curious to hear your feedback!

Here is the comparison video. Your repo is on the left; my fork is on the right.

https://github.com/user-attachments/assets/17db29df-532f-467a-b734-918c26ce2c4a

### CODE REVIEW

**Comment by vladstudio** [comment]
testing with more themes...

https://github.com/user-attachments/assets/ff418f00-53e6-4188-aa6c-7a147afa5b02

**Comment by saoudrizwan** [comment]
What! This is so cool, I'll play around with this!

**Comment by vladstudio** [comment]
In retrospect, I should have been much more granular in my suggestions. The recent upstream update introduces many conflicts, which are probably not worth resolving. I'll close this PR and maybe will send some other PRs with very local changes that would be much easir to review.

**Comment by saoudrizwan** [comment]
Thank you for being so considerate @vladstudio

**Pull request closed without merging**
