### PR TITLE
Implement comprehensive task history feature

### PR DESCRIPTION
**Pull request by loicboutet**
This commit introduces a robust task history feature to the application, enhancing user experience and functionality. Key changes include:

1. TaskHistoryManager (src/TaskHistoryManager.ts):
   - Implemented core functionality for managing task history
   - Added methods for adding, retrieving, and updating tasks
   - Integrated with VSCode's extension context for persistent storage

2. HistoryManager (src/HistoryManager.ts):
   - Extended TaskHistoryManager with additional features
   - Introduced MessageFormatter for consistent message formatting
   - Implemented methods for adding messages to existing tasks

3. TaskHistoryView (webview-ui/src/components/TaskHistoryView.tsx):
   - Created a new React component for displaying task history
   - Implemented UI for listing tasks with timestamps and message counts
   - Added functionality to select tasks and clear history

4. Integration changes:
   - Updated ClaudeDev.ts, extension.ts, and SidebarProvider.ts to incorporate the new history feature
   - Modified existing components (ChatView, ChatRow, WelcomeView) to support task history

5. New utility classes:
   - Added ApiHandler.ts for API-related operations
   - Introduced Constants.ts for managing constant values
   - Created ToolExecutor.ts for handling tool executions

6. Package updates:
   - Updated package.json files to include new dependencies and scripts

This feature allows users to review past tasks, improving continuity and reference capabilities within the application.

### CODE REVIEW

**Comment by mkearl** [comment]
This is awesome can't wait till this gets applied

**Comment by Balatzar** [comment]
Thank you very much! You can try this and other features (automatic approuval, git branch creation...) in [this fork](https://github.com/loicboutet/claude-dev) if you want :)

**Comment by mkearl** [comment]
Awesome I will check it out.  The only problem with this is the rate limits.   I would love to see this working with new llama 3.1/ ollama which now supports tools    Sent from my iPhoneOn Jul 27, 2024, at 12:30 PM, Balthazar Aubard ***@***.***> wrote:﻿
Thank you very much! You can try this and other features (automatic approuval, git branch creation...) in this fork if you want :)

**Comment by mkearl** [comment]
I just tried this out and it is working great!  Excellent Job. I like your implementation of history.   And the autocomplete worked very well on the small example I tried.

 It would be nice to have a button on the history to copy to clipboard 


Do you know if this functionality for this extension could have the same functionality using LLAMA3.1 ?  I would use this a log with Claude but they limit you so bad on token use per day.

**Comment by gfsysa** [comment]
bump for these features -- nice work!

**Comment by alexpvpmindustry** [comment]
am interested to have this as well!

**Comment by BartNetJS** [comment]
can't wait for it 👍

**Pull request closed without merging**
