### PR TITLE
Add 'Always allow write operations' option

### PR DESCRIPTION
**Pull request by TKasperczyk**
Introduces a new user preference to opt out of manual approval for file write operations, similar to the existing "Always allow read-only operations" setting.

Key changes:

- Added a new user preference toggle: "Always allow write operations"
- Modified the ClaudeDev class to incorporate this option
- Updated the writeToFile method to bypass user confirmation when enabled
- Added a new checkbox in the Settings view
- Updated relevant interfaces and message types to include the new option

### CODE REVIEW

**Comment by TKasperczyk** [comment]
If both "Always allow read-only operations" and "Always allow write operations" are enabled, the agent could enter an endless loop without user intervention. This removes the user's ability to provide feedback or interrupt the process, which is normally done through the approval dialogs.

@saoudrizwan, what do you think would be the best strategy to address this? One potential solution could be adding an "Interrupt" button that stops the loop after the next API call, allowing the user to provide feedback in the message input box. This would maintain the full autonomy with auto-approvals while still giving users control when needed.

**Comment by msti** [comment]
I agree with @TKasperczyk and think that the addition of an "Interupt" or "Stop" button is useful regardless of the new "Always allow write operations" There have been times that I submit the prompt but then immediately change my mind and want to amend to it.

**Comment by hhopkins95** [comment]
Another idea could be to enable batch approval of write operations, where claude wants to update multiple files in the context of a single task (feat update, multi-file component...) -- not necessarily the same feature as above, but could improve the UX in similar situations. Should prevent loops as well

**Comment by Sarke** [comment]
I think decent solution would be to have an option like "**Allow N number of actions without user input**". Say you set it to 10, then after 10 actions there would be a new "**Approve**"/"**Reject**" question, or even just a simple "**Continue**"

**Comment by hemeda3** [comment]
any idea when this could be solved please

**Pull request closed without merging**
