### PR TITLE
Add Vertex AI support

### PR DESCRIPTION
**Pull request by u-minor**
This PR adds support for Vertex AI in Google Cloud.
~~At this time, the Application Default Credentials (ADC) must be set in the gcloud command to use Vertex AI.~~

Authentication supports one of the following.
- Application Default Credentials (ADC)
    - needs gcloud CLI
- Service Account Key

### CODE REVIEW

**Comment by EasyChris** [comment]
nice pr can you provide more detail to tell us how to config with Google cloud？

**Comment by u-minor** [comment]
@EasyChris 

Below is a simple setup procedure.

1. Enable Vertex AI API and Claude 3.5 Sonnet model in your own project in Google Cloud Console
    https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude
2. Install gcloud CLI and configure ADC
    https://cloud.google.com/docs/authentication/provide-credentials-adc
3. Configure claude-dev
    - API Provider: GC Vertex AI
    - Google Cloud Project ID: `<Your project ID>`
    - Google Cloud Region: us-east5 or europe-west1
        > Claude 3.5 Sonnet is available in the following regions:
        > - us-east5 (Ohio)
        > - europe-west1 (Belgium)

**Comment by xavitg** [comment]
It doesn't work for me. I am using Cloud Shell on Google Cloud and I set up my project id and location. When I write the prompt, it does nothing and it gets blocked. 

1: I send the prompt
image

2: I cannot interact anymore and also don't get any feedback from the extension:
image

**Comment by saoudrizwan** [comment]
Hi @u-minor thank you for the contribution! For security reasons I don't accept PRs that change the package-lock.json, so please uninstall the `@anthropic-ai/vertex-sdk` package and I will install that myself after I've merged your changes.

**Comment by u-minor** [comment]
Hi @saoudrizwan, I rebased branch and removed changes in package.json.

**Comment by s106916** [comment]
Hi @u-minor, Could you please add the vertex models: gemini-flash and gemini-pro within this PR?

**Comment by u-minor** [comment]
@saoudrizwan Followed the latest main branch.

**Comment by u-minor** [comment]
> Hi @u-minor, Could you please add the vertex models: gemini-flash and gemini-pro within this PR?

@s106916 Sorry, this PR uses @anthropic-ai/vertex-sdk and is not intended for use with non-anthropic models.

**Comment by giranntu** [comment]
@u-minor much appreiciated of your work! that is super super awesome!!! and being tested it works for me.

**Comment by giranntu** [comment]
could we set the output token to 8192 which makes it could handling the long coding task?

**Comment by u-minor** [comment]
> could we set the output token to 8192 which makes it could handling the long coding task?

@giranntu 
I tried adding a custom header in the same way as `api/anthropic.ts`, but could not raise max_tokens  and got the following error...

```
API Request Failed
400 {"type":"error","error":{"type":"invalid_request_error","message":"max_tokens: 8192 > 4096, which is the maximum allowed number of output tokens for claude-3-5-sonnet-20240620"}}
```

**Comment by giranntu** [comment]
> > could we set the output token to 8192 which makes it could handling the long coding task?
> 
> @giranntu I tried adding a custom header in the same way as `api/anthropic.ts`, but could not raise max_tokens and got the following error...
> 
> ```
> API Request Failed
> 400 {"type":"error","error":{"type":"invalid_request_error","message":"max_tokens: 8192 > 4096, which is the maximum allowed number of output tokens for claude-3-5-sonnet-20240620"}}
> ```

thanks @u-minor  it might be the current issue for vertex AI couldn't add the additional header, and will wait if we could solve it for the future release.

**Comment by achhabra2** [comment]
Vertex does not currently support the beta features as they are pre-release and in testing, but they will be supported once GA

**Comment by u-minor** [comment]
@saoudrizwan 
Added support for service account keys.

https://github.com/saoudrizwan/claude-dev/issues/83#issuecomment-2290208269

1. Create a new service account in IAM & admin -> Service Accounts
    e.g. `claude-dev` (claude-dev@****.iam.gserviceaccount.com)
2. Create new key (JSON) for the created service account and download credential json
3. Attach `Vertex AI User` role to the created service account in IAM & admin -> IAM
4. base64 encode the credential json as follows
    `base64 -w0 ****.json`
    > Please be careful not to use online Base64 encoding tools

**Comment by fry69** [comment]
I tested authentication via Service Account Key (macOS `base64` does not understand `-w0` btw, just leaving that out worked converting the `.json` file to an unbroken Base64 string)  and I can confirm that this works, Sonnet-3.5 is happily answering requests this way via Vertex AI / GCP.

BTW: I did not have to create a new Service Account for this to get this working, it worked using the "Compute Engine Default Service Account", which gets automatically created for every new project in GCP (it seems). Or is this a bad idea somehow? (I am using GCP only for a week or so, I do not really have a clue what I am doing in this complex thing, but it works for me so far)

**Comment by u-minor** [comment]
Hi @fry69 
> macOS base64 does not understand -w0
Sorry, I was using the base64 coreutils version installed with homebrew.

> is using this account a bad idea somehow?
As the default compute service account has a very strong ‘Editor role’, I strongly recommend creating a dedicated service account with only the ‘Vertex AI User role’.

**Comment by fry69** [comment]
> > is using this account a bad idea somehow?
> 
> As the default compute service account has a very strong `Editor` role, I strongly recommend creating a dedicated service account with only the `Vertex AI User` role.

Thank you! 👍 I'll create a new Service Account.

**Comment by u-minor** [comment]
@giranntu
Now support 8192 tokens for claude-3-5-sonnet@20240620!

https://x.com/alexalbert__/status/1825920737326281184

**Comment by fry69** [comment]
> what is the hold-back to get that merged

I can't speak for @saoudrizwan, but from my experience a little guidance in form of a short howto is needed to successfully connect to Claude models through Vertex AI. This is not trivial/self explanatory, IMHO.

**Comment by giranntu** [comment]
@saoudrizwan, @u-minor has successfully addressed all concerns and added valuable features:

- Vertex AI support implemented and tested
- Service account key authentication added
- Max tokens increased to 8192 for claude-3-5-sonnet
- Package-lock.json changes removed as requested
-  The community is eager to use this feature. Are there any remaining blockers? If not, can we set a target date for merging?

@fry69, most GCP users are familiar with basic operations. We can proceed with this version that works for the majority, and refine based on user feedback if needed. This approach allows us to get the feature out quickly while leaving room for future improvements.

Let's aim to merge this week. The incremental improvements approach will benefit users sooner rather than later. Thanks to all contributors for their efforts and patience.

**Comment by fry69** [comment]
Workaround until this PR gets merged:

Build from source and generate VSIX, then install from VSIX in VSCode, with these simple instructions:

```shell
$ git clone https://github.com/saoudrizwan/claude-dev
$ cd claude-dev
$ git fetch origin pull/45/head:vertexai
$ git switch -c localbuild
$ git merge vertexai # should not produce merge errors
$ npm add google-auth-library @anthropic-ai/vertex-sdk
$ git add . && git commit -m "[WIP] add necessary dependencies"
$ npm run install:all
$ npm install -g vsce
$ vsce package
```

And install the generated package e.g. `claude-dev-1.3.4.vsix` inside VSCode.
Repeat if new version gets released (and fix possible merge conflicts).

**Comment by saoudrizwan** [comment]
Sorry it wasn't my intention to not accept the PR, in fact it helped me a ton. There were just a couple things I had to do differently + merge conflicts. I will try to be more ontop of PRs in the future.

**Pull request closed without merging**
