### PR TITLE
set line height to 1.5em everywhere

### PR DESCRIPTION
**Pull request by vladstudio**
This couple of CSS lines solves the most pressing design problem: not enough space between lines.

### CODE REVIEW

**Comment by vladstudio** [comment]
here's before and after (you may say now there's less text on screen, but I'd say that readability is more important)

image

**Comment by saoudrizwan** [comment]
Hey! I'll have to play around with this lineheight change, but i wanted to chime in and let you know v1.6.3 has some visual updates that I think you'll like! The syntax highlighting should be better (and faster) + you can collapse the task header now too + tons of other smaller ux improvements. 
Cursor 2024-09-10 22 06 21

**Comment by vladstudio** [comment]
It's so nice of you to mention that, thanks! :-) To test the line height, simply switch between Claude-dev and any other sidebar that is native (not web view) and has multi-line text (e.g. Run and Debug). You'll notice the difference.

image

**Comment by saoudrizwan** [comment]
Thank you @vladstudio for pushing this suggestion, I was playing around with line heights today and you're right the webview sets the line height to 1.2 while everywhere else its 1.3-1.4. VSCode sets a lot of other default css so I assumed it just used system line height but that's not the case.

**Pull request merged**
